apiVersion: v1
kind: Service
metadata:
  name: mlops-api-service
  namespace: production
  labels:
    app: mlops-api
spec:
  type: ClusterIP
  selector:
    app: mlops-api
    environment: blue  # Initially points to blue
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-api-loadbalancer
  namespace: production
  labels:
    app: mlops-api
spec:
  type: LoadBalancer
  selector:
    app: mlops-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlops-api-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.mlops.example.com
    secretName: mlops-api-tls
  rules:
  - host: api.mlops.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mlops-api-service
            port:
              number: 80